---
- name: Run MongoDB Container
  docker_container:
    name: yolo-database-container
    image: mongo:jammy
    state: started
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    networks:
      - name: yolo_network
  tags:
    - database
    - backend
