---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  roles:
    - docker-installation
    - repo-clone
    - network-setup
    - data-container
    - database-setup
    - backend-deploy
    - frontend-deploy
