---
# Install and configure docker on Debian/Ubuntu hosts.
- block:

    - name: install prerequisites
      apt:
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      tags:
        - docker
    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      tags:
        - docker
    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      tags:
        - docker
    - name: install docker
      apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      tags:
        - docker
    - name: add userpermissions
      shell: 'usermod -aG docker vagrant'
      tags:
        - docker
  when: ansible_os_family == 'Debian'
  rescue:
    - name: Handle error during docker installation
      debug:
        msg: 'Docker installation failed. Please check the logs.'
